#!/usr/bin/env python3
"""Generate src/tzdata.c from /usr/share/zoneinfo. Run manually to refresh."""

import os

ZONEINFO = "/usr/share/zoneinfo"
OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "tzdata.c")
DROP_PREFIXES = ("Brazil/", "Canada/", "Chile/", "Mexico/")


def posix_trailer(path):
    with open(path, "rb") as f:
        data = f.read()
    if not data.startswith(b"TZif"):
        return None
    parts = data.split(b"\n")
    return parts[-2].decode("ascii") if len(parts) >= 2 and parts[-2] else None


zones = {}
for dp, _, fns in os.walk(ZONEINFO, followlinks=False):
    for n in fns:
        path = os.path.join(dp, n)
        posix = posix_trailer(path)
        if posix is None:
            continue
        name = os.path.relpath(path, ZONEINFO).replace(os.sep, "/")
        if "/" not in name or name.startswith(DROP_PREFIXES):
            continue
        zones[name] = posix

version = open(os.path.join(ZONEINFO, "+VERSION")).read().strip()

with open(OUTPUT, "w") as f:
    f.write(f"// Generated by gen_tzdata.py — do not edit by hand.\n")
    f.write(f"// Source: IANA tzdata {version}\n\n")
    f.write('#include "tzdata.h"\n\n')
    f.write(f"const size_t naos_tzdata_count = {len(zones)};\n\n")
    f.write("const naos_tzdata_entry_t naos_tzdata[] = {\n")
    for name in sorted(zones):
        f.write(f'    {{"{name}", "{zones[name]}"}},\n')
    f.write("};\n")

print(f"wrote {len(zones)} zones from tzdata {version} to {OUTPUT}")
