package tree

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"tinygo.org/x/espflasher/pkg/nvs"
)

func TestCollectValues(t *testing.T) {
	// read partition generated by the ESP-IDF partition generator, which
	// contains values in the "naos" and "naos-ble" namespaces
	data, err := os.ReadFile(filepath.Join("testdata", "nvs.bin"))
	if err != nil {
		t.Fatal(err)
	}

	// parse partition
	entries, err := nvs.ParseNVS(data)
	if err != nil {
		t.Fatal(err)
	}

	// collect values, dropping the binary value and the other namespace
	values := collectValues(entries, nil)
	want := map[string]string{
		"wifi-ssid":   "WS",
		"device-name": "hello-world",
		"mqtt-port":   "1234",
		"long":        strings.Repeat("L", 5000),
	}
	if !reflect.DeepEqual(values, want) {
		for key, value := range values {
			t.Logf("%s = %q", key, value)
		}
		t.Errorf("unexpected values")
	}
}

func TestGenerateImage(t *testing.T) {
	// prepare values that cover an empty value, a value that is split into
	// multiple chunks and a value that contains a comma
	values := map[string]string{
		"wifi-ssid":   "WS",
		"device-name": "hello-world",
		"empty":       "",
		"comma":       "a,b",
		"long":        strings.Repeat("L", 5000),
	}

	// generate image
	image, err := generateImage(values, 0x6000)
	if err != nil {
		t.Fatal(err)
	}

	// parse image
	entries, err := nvs.ParseNVS(image)
	if err != nil {
		t.Fatal(err)
	}

	// collect values
	got := collectValues(entries, nil)
	if !reflect.DeepEqual(got, values) {
		for key, value := range got {
			t.Logf("%s = %q", key, value)
		}
		t.Errorf("unexpected values")
	}
}

func TestReadPartitions(t *testing.T) {
	// read table built for the test project
	data, err := os.ReadFile(filepath.Join("testdata", "partition-table.bin"))
	if err != nil {
		t.Fatal(err)
	}

	// parse table
	partitions := parsePartitions(data)
	want := []partition{
		{Name: "nvs", Offset: 0x9000, Size: 16 * 1024},
		{Name: "otadata", Offset: 0xd000, Size: 8 * 1024},
		{Name: "phy_init", Offset: 0xf000, Size: 4 * 1024},
		{Name: "alpha", Offset: 0x10000, Size: 1592 * 1024},
		{Name: "beta", Offset: 0x1a0000, Size: 1592 * 1024},
		{Name: "storage", Offset: 0x32e000, Size: 528 * 1024},
		{Name: "coredump", Offset: 0x3b2000, Size: 64 * 1024},
	}
	if !reflect.DeepEqual(partitions, want) {
		for _, p := range partitions {
			t.Logf("%s: offset 0x%x size 0x%x", p.Name, p.Offset, p.Size)
		}
		t.Errorf("unexpected partitions")
	}
}
