package tree

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"tinygo.org/x/espflasher/pkg/nvs"
)

func TestParseSize(t *testing.T) {
	for _, item := range []struct {
		str  string
		want int64
	}{
		{"0x4000", 0x4000},
		{"0x61999", 0x61999},
		{"16K", 16 * 1024},
		{"1756K", 1756 * 1024},
		{"1M", 1024 * 1024},
		{"4096", 4096},
	} {
		got, err := parseSize(item.str)
		if err != nil {
			t.Fatalf("%s: %v", item.str, err)
		}
		if got != item.want {
			t.Errorf("%s = %d, want %d", item.str, got, item.want)
		}
	}

	// the generator never emits these, but they must not parse as zero
	for _, str := range []string{"", "abc", "0xZZ"} {
		if _, err := parseSize(str); err == nil {
			t.Errorf("expected %q to fail", str)
		}
	}
}

func TestCollectValues(t *testing.T) {
	// read partition generated by the ESP-IDF partition generator, which
	// contains values in the "naos" and "naos-ble" namespaces
	data, err := os.ReadFile(filepath.Join("testdata", "nvs.bin"))
	if err != nil {
		t.Fatal(err)
	}

	// parse partition
	entries, err := nvs.ParseNVS(data)
	if err != nil {
		t.Fatal(err)
	}

	// collect values, dropping the binary value and the other namespace
	values := collectValues(entries, nil)
	want := map[string]string{
		"wifi-ssid":   "WS",
		"device-name": "hello-world",
		"mqtt-port":   "1234",
		"long":        strings.Repeat("L", 5000),
	}
	if !reflect.DeepEqual(values, want) {
		for key, value := range values {
			t.Logf("%s = %q", key, value)
		}
		t.Errorf("unexpected values")
	}
}
