on: [push, pull_request]
name: Component
jobs:
  com:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            com/test/esp-idf
            com/test/tools
            com/test/components/esp-mqtt
            com/test/components/esp-osc
          key: v0-${{ runner.os }}-${{ hashFiles('tree/*.version') }}

      - name: Prepare
        run: sudo apt-get install python-is-python3 gperf -y

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd com; make prepare install

      - name: Update
        if: steps.cache.outputs.cache-hit == 'true'
        run: cd com; make update

      - name: Build
        run: cd com; make reconfigure build
