on: [push, pull_request]
name: Component
jobs:
  com:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: sudo apt-get install python-is-python3 gperf -y

      - name: Prepare
        run: cd com; make prepare

      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: com/test/tools
          key: v0-${{ runner.os }}-${{ hashFiles('tree/esp-idf.version') }}

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd com; make install

      - name: Build
        run: cd com; make reconfigure build
