on: [push, pull_request]
name: Component
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: sudo apt-get install python-is-python3 gperf -y

      - name: Test Component
        run: |
          cd com
          make prepare install
          make build
