on: [push, pull_request]
name: Component
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            com/test/esp-idf
            com/test/components/esp-mqtt
            com/test/components/esp-osc
          key: ${{ runner.os }}-${{ hashFiles('tree/*.version') }}

      - name: Prepare
        run: sudo apt-get install python-is-python3 gperf -y

      - name: Test
        run: |
          cd com
          make prepare install
          make build
