on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Prepare
        run: sudo apt-get install python-is-python3 gperf bluez -y

      - name: Test Component
        run: |
          cd com
          make prepare install
          make build

      - name: Test CLI
        run: go test ./...

      - name: Build CLI
        run: |
          env GOOS=darwin GOARCH=amd64 go build -o naos-darwin-amd64 ./cmd/naos
          env GOOS=darwin GOARCH=arm64 go build -o naos-darwin-arm64 ./cmd/naos
          env GOOS=linux GOARCH=amd64 go build -o naos-linux-amd64 ./cmd/naos

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            naos-darwin-amd64
            naos-darwin-arm64
            naos-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
