on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Component
        run: |
          sudo apt-get install python-is-python3 gperf -y
          cd com; make test/xtensa-esp32-elf test/esp-idf test/components/esp-mqtt
          cd com; /usr/bin/python -m pip install --user -r test/esp-idf/requirements.txt
          cd com; make build
      - name: Test CLI
        run: go test ./...
      - name: Build CLI
        run: |
          env GOOS=darwin GOARCH=amd64 go build -o naos-darwin-amd64 ./cmd/naos
          env GOOS=linux GOARCH=amd64 go build -o naos-linux-amd64 ./cmd/naos
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            naos-darwin-amd64
            naos-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
